import json
# One editorial entry per state. Sources retrieved September 2026.
rows=[
(1,'Aguascalientes','Museo Regional de Historia','Aguascalientes','Edificio histórico','Siglos XIX–XX','Una casa del arquitecto Refugio Reyes alberga un recorrido por la historia regional. El propio edificio ayuda a observar cómo cambia el uso de los espacios con el tiempo.','Observa la fachada y compara el edificio con los objetos de sus salas.','¿Qué puede contar una casa acerca de la ciudad que la rodea?','https://www.inah.gob.mx/museos/museo-regional-de-historia-de-aguascalientes','INAH','nacion'),
(2,'Baja California','El Vallecito','Tecate · La Rumorosa','Sitio arqueológico','México antiguo','Los abrigos rocosos conservan pinturas y grabados del estilo La Rumorosa. Sus figuras permiten estudiar formas de representación del pasado del norte de México.','Distingue figuras geométricas y humanas en las imágenes oficiales.','¿Qué podemos describir de una pintura sin asegurar todavía qué significa?','https://www.inah.gob.mx/zonas/zona-arqueologica-el-vallecito','INAH',''),
(3,'Baja California Sur','Museo de las Misiones de Loreto','Loreto','Edificio histórico','Periodo virreinal','El museo ocupa el antiguo Almacén General, junto a la misión de Nuestra Señora de Loreto. Permite investigar las misiones y las transformaciones de la península.','Compara el antiguo uso del inmueble con su función como museo.','¿Cómo cambió la vida de las comunidades con el establecimiento de las misiones?','https://lugares.inah.gob.mx/es/node/4508','INAH',''),
(4,'Campeche','Baluarte de la Soledad','San Francisco de Campeche','Fortificación','Periodo virreinal','Esta construcción militar de finales del siglo XVII formó parte de la defensa de Campeche. Hoy alberga el Museo de Arquitectura Maya.','Distingue el edificio defensivo de las piezas mayas que resguarda.','¿Por qué un museo puede reunir objetos más antiguos que el edificio donde se encuentran?','https://www.inah.gob.mx/museos/museo-de-arquitectura-maya-baluarte-de-la-soledad','INAH','mesoamerica'),
(5,'Coahuila','Museo de los Presidentes Coahuilenses','Saltillo','Museo histórico','Siglos XIX–XX','El museo reúne documentos y objetos relacionados con cinco coahuilenses que ocuparon la presidencia. Ayuda a conectar biografías regionales con procesos nacionales.','Elige un documento y registra autor, fecha y destinatario.','¿Qué diferencia hay entre conocer la vida de un presidente y explicar todo un proceso histórico?','https://coahuilacultura.gob.mx/museos-de-coahuila/museo-de-los-presidentes/','Secretaría de Cultura de Coahuila','revolucion'),
(6,'Colima','La Campana','Villa de Álvarez','Sitio arqueológico','México antiguo','Los vestigios de esta ciudad forman parte del patrimonio arqueológico del occidente mesoamericano. Se encuentran dentro de la actual zona metropolitana de Colima.','Compara el plano del sitio con la ciudad que hoy lo rodea.','¿Cómo puede convivir una ciudad actual con los restos de una ciudad antigua?','https://lugares.inah.gob.mx/es/node/4425','INAH','mesoamerica'),
(7,'Chiapas','Palenque','Palenque','Sitio arqueológico','México antiguo','La antigua ciudad maya conserva arquitectura e inscripciones que permiten investigar a sus gobernantes y su historia. Su nombre actual procede de la población vecina.','Observa los edificios y pregunta qué aportan las inscripciones a su estudio.','¿Qué puede revelar un texto antiguo que un edificio por sí solo no explica?','https://www.inah.gob.mx//zonas/zona-arqueologica-palenque','INAH','mesoamerica'),
(8,'Chihuahua','Paquimé','Casas Grandes','Sitio arqueológico','México antiguo','Paquimé permite explorar la arquitectura de tierra y los intercambios entre sociedades del norte y Mesoamérica. Su historia muestra que el México antiguo fue culturalmente diverso.','Observa la organización de los espacios y los materiales de construcción.','¿Por qué sería insuficiente estudiar todas las ciudades antiguas como si fueran iguales?','https://lugares.inah.gob.mx/es/node/4353','INAH','mesoamerica'),
(9,'Ciudad de México','Castillo de Chapultepec','Bosque de Chapultepec','Edificio histórico','Siglos XVIII–XX','El castillo tuvo usos como residencia y escenario de episodios de la historia nacional. Hoy es sede del Museo Nacional de Historia.','Distingue la historia del edificio de la historia representada en sus colecciones.','¿Cómo cambia el significado de un lugar cuando se convierte en museo?','https://mnh.inah.gob.mx/historia-del-museo','INAH','nacion'),
(10,'Durango','La Ferrería','Valle del Guadiana · Durango','Sitio arqueológico','México antiguo','La Ferrería fue un centro de la cultura Chalchihuites. Su ubicación en un cerro y su relación con el valle permiten explorar territorio y organización social.','Observa cómo se distribuyen los espacios sobre el relieve.','¿Qué ventajas y dificultades tiene construir una población en un cerro?','https://www.inah.gob.mx/zonas/zona-arqueologica-la-ferreria','INAH','mesoamerica'),
(11,'Guanajuato','Alhóndiga de Granaditas','Guanajuato','Edificio histórico','Independencia','El antiguo almacén de granos fue escenario de una batalla de la insurgencia el 28 de septiembre de 1810. También tuvo otros usos antes de convertirse en museo regional.','Relaciona el uso original del edificio con su transformación durante un conflicto.','¿Por qué un mismo edificio puede guardar memorias muy diferentes?','https://lugares.inah.gob.mx/es/node/4245?page=1','INAH','independencia'),
(12,'Guerrero','Fuerte de San Diego','Acapulco','Fortificación','Periodo virreinal e Independencia','La fortaleza permite investigar la historia del puerto, el comercio por el Pacífico y episodios de la lucha de Morelos. Es sede del Museo Histórico de Acapulco.','Relaciona la fortaleza con la costa y con la actividad portuaria.','¿Qué relación existe entre comercio, puertos y construcciones defensivas?','https://www.inah.gob.mx//museos/museo-historico-de-acapulco-fuerte-de-san-diego','INAH','independencia'),
(13,'Hidalgo','Tula','Tula de Allende','Sitio arqueológico','México antiguo','La antigua ciudad de Tollan-Xicocotitlan alcanzó gran importancia durante el Posclásico temprano. Sus redes de intercambio ayudan a estudiar conexiones entre regiones.','Observa la escala de las esculturas y su relación con la arquitectura.','¿Cómo se investiga la influencia de una ciudad en lugares distantes?','https://www.inah.gob.mx/zonas/zona-arqueologica-y-museo-de-sitio-de-tula','INAH','mesoamerica'),
(14,'Jalisco','Guachimontones','Teuchitlán','Sitio arqueológico','México antiguo','Los conjuntos circulares son una expresión distintiva de la tradición Teuchitlán. Este sitio muestra otras formas de organizar el espacio en el occidente de México.','Compara una planta circular con una plaza rectangular.','¿La forma de un espacio influye en cómo se reúne una comunidad?','https://www.inah.gob.mx/zonas/zona-arqueologica-teuchitlan-o-guachimontones','INAH','mesoamerica'),
(15,'Estado de México','Teotihuacan','Valle de Teotihuacán','Sitio arqueológico','México antiguo','Una gran ciudad del periodo Clásico, con edificios monumentales, conjuntos habitacionales y redes de intercambio. Los mexicas le dieron su nombre conocido después de su apogeo.','Compara los espacios monumentales con la información sobre las viviendas.','¿Por qué una ciudad no puede explicarse solamente por sus pirámides?','https://www.inah.gob.mx/boletines/historia-breve-de-teotihuacan','INAH','mesoamerica'),
(16,'Michoacán','Tzintzuntzan','Tzintzuntzan · lago de Pátzcuaro','Sitio arqueológico','México antiguo','Fue capital del señorío purépecha o tarasco y un centro de decisiones políticas, económicas y religiosas. Sus terrazas muestran una adaptación al relieve de la región.','Relaciona las plataformas con el paisaje del lago y las laderas.','¿Qué funciones podía concentrar una capital además de las religiosas?','https://www.inah.gob.mx/zonas/zona-arqueologica-de-tzintzuntzan','INAH','mesoamerica'),
(17,'Morelos','Xochicalco','Miacatlán y Temixco','Sitio arqueológico','México antiguo','Esta ciudad del Epiclásico se construyó sobre cerros. Permite explorar las relaciones entre paisaje, arquitectura y organización del territorio.','Observa el emplazamiento elevado y los relieves de sus construcciones.','¿Qué información del entorno obtiene quien observa desde lo alto?','https://www.inah.gob.mx/zonas/zona-arqueologica-de-xochicalco','INAH','mesoamerica'),
(18,'Nayarit','Ixtlán del Río · Los Toriles','Ixtlán del Río','Sitio arqueológico','México antiguo','El sitio conserva un templo de base circular que ayuda a reconocer la diversidad arquitectónica del occidente. El nombre popular Los Toriles alude a su forma.','Distingue la forma observada de la interpretación sobre su función.','¿Un nombre popular basta para explicar el uso original de un edificio?','https://lugares.inah.gob.mx/es/node/4421','INAH','mesoamerica'),
(19,'Nuevo León','El Obispado','Monterrey','Edificio histórico','Periodo virreinal','El edificio del siglo XVIII se alza en la Loma de Chepe Vera. Es sede del Museo Regional de Nuevo León y permite vincular arquitectura e historia regional.','Compara su ubicación elevada con el crecimiento de Monterrey.','¿Cómo cambia el entorno de un edificio histórico cuando crece una ciudad?','https://www.inah.gob.mx/museos/museo-regional-de-nuevo-leon','INAH','nacion'),
(20,'Oaxaca','Monte Albán','Valles Centrales de Oaxaca','Sitio arqueológico','México antiguo','Esta ciudad antigua permite investigar la historia de los Valles Centrales. El área protegida se extiende por varios municipios actuales.','Relaciona la plaza principal con la posición del asentamiento sobre el valle.','¿Por qué las fronteras municipales actuales no explican por sí solas una ciudad antigua?','https://www.inah.gob.mx/zonas/94-zona-arqueologica-de-monte-alban','INAH','mesoamerica'),
(21,'Puebla','Fuerte de Loreto','Puebla de Zaragoza','Fortificación','Siglo XIX','El recinto forma parte de los lugares vinculados con la defensa de Puebla. El Museo de la No Intervención permite estudiar los conflictos internacionales del siglo XIX.','Contrasta un objeto o documento del museo con una narración de la batalla.','¿Qué fuentes usarías para explicar una batalla sin depender de una sola versión?','https://www.inah.gob.mx/museos/museo-del-fuerte-de-loreto','INAH','nacion'),
(22,'Querétaro','Teatro de la República','Santiago de Querétaro','Edificio histórico','Revolución y Constitución','Conocido entonces como Teatro Iturbide, fue el recinto del Congreso Constituyente. Allí se juró la Constitución el 5 de febrero de 1917.','Imagina cómo se organiza un espacio destinado a escuchar y debatir.','¿Por qué debatir una ley no garantiza que todos sus derechos se cumplan de inmediato?','https://www.gob.mx/shcp/articulos/8-cosas-que-quiza-no-conocias-sobre-la-constitucion1917','Secretaría de Hacienda y Crédito Público','revolucion'),
(23,'Quintana Roo','Tulum','Tulum','Sitio arqueológico','México antiguo','La ciudad maya se sitúa junto al mar Caribe. Conserva edificios con pintura mural y relieves que forman parte de los trabajos de investigación y conservación.','Relaciona el emplazamiento costero con las preguntas sobre comunicación e intercambio.','¿Qué preguntas históricas sugiere una ciudad construida frente al mar?','https://www.inah.gob.mx/boletines/el-promeza-ayuda-a-integrar-base-precisa-sobre-la-conservacion-de-murales-y-bienes-decorativos-de-tulum','INAH','mesoamerica'),
(24,'San Luis Potosí','Tamtoc','Tamuín · Huasteca potosina','Sitio arqueológico','México antiguo','Tamtoc permite explorar la historia urbana de la Huasteca. Las excavaciones, esculturas y construcciones aportan evidencias para reconstruir la vida de sus habitantes.','Pregunta qué aporta un hallazgo junto con su contexto de excavación.','¿Por qué una pieza pierde información si se separa del lugar donde fue encontrada?','https://lugares.inah.gob.mx/es/node/4460','INAH','mesoamerica'),
(25,'Sinaloa','Las Labradas','San Ignacio','Sitio arqueológico','México antiguo','Los petrograbados se distribuyen en rocas de una franja costera. Son una oportunidad para observar formas de representación y su relación con el paisaje.','Describe líneas y figuras antes de proponer qué podrían significar.','¿Cómo distinguirías una observación de una interpretación de estos grabados?','https://www.inah.gob.mx/zonas/zona-arqueologica-de-las-labradas','INAH',''),
(26,'Sonora','Cerro de Trincheras','Trincheras','Sitio arqueológico','México antiguo','Las terrazas de piedra y los espacios comunales son elementos destacados del asentamiento. Muestran formas de habitar y organizar un cerro en el noroeste.','Observa la relación entre las terrazas y la pendiente.','¿Qué conocimientos se necesitan para adaptar un asentamiento a un cerro?','https://www.inah.gob.mx//zonas/zona-arqueologica-trincheras','INAH',''),
(27,'Tabasco','Comalcalco','Comalcalco','Sitio arqueológico','México antiguo','La ciudad maya se desarrolló en el paisaje de ríos y lagunas de Tabasco. La investigación de sus edificios y objetos permite estudiar vida cotidiana e intercambios.','Relaciona el sitio con su entorno fluvial y lagunar.','¿Cómo puede influir el agua en la ubicación y las actividades de una ciudad?','https://lugares.inah.gob.mx/es/node/4390','INAH','mesoamerica'),
(28,'Tamaulipas','El Sabinito','Soto la Marina','Sitio arqueológico','México antiguo','Los vestigios del asentamiento y objetos como vasijas, herramientas y cuentas permiten explorar el pasado de esta región de Tamaulipas.','Compara lo que informa una herramienta con lo que informa una construcción.','¿Qué objetos usarías para investigar alimentación, trabajo o intercambio?','https://lugares.inah.gob.mx/es/node/4405','INAH',''),
(29,'Tlaxcala','Cacaxtla–Xochitécatl','Nativitas','Sitio arqueológico','México antiguo','Cacaxtla floreció durante el Epiclásico y mantuvo relaciones con otras regiones. El conjunto permite pensar en redes de comunicación y expresiones visuales del pasado.','Compara una imagen mural con el lugar arquitectónico donde se encuentra.','¿Qué cambia al estudiar una imagen dentro de su contexto original?','https://lugares.inah.gob.mx/es/node/4332','INAH','mesoamerica'),
(30,'Veracruz','El Tajín','Papantla','Sitio arqueológico','México antiguo','La ciudad tuvo influencia en las cuencas de los ríos Cazones y Tecolutla. Sus edificios y juegos de pelota permiten explorar arquitectura y relaciones regionales.','Compara las formas y dimensiones de distintos espacios del sitio.','¿Qué diferencias entre edificios podrían sugerir funciones distintas?','https://www.inah.gob.mx/zonas/153-zona-arqueologica-el-tajin-y-museo-de-sitio','INAH','mesoamerica'),
(31,'Yucatán','Uxmal','Santa Elena · región Puuc','Sitio arqueológico','México antiguo','La arquitectura de Uxmal forma parte de la historia maya de la región Puuc. Sus edificios permiten observar relaciones entre arte, paisaje y organización del espacio.','Observa patrones y detalles arquitectónicos en la galería oficial.','¿Qué elementos se repiten y qué preguntas sugieren esas repeticiones?','https://lugares.inah.gob.mx/es/node/4482','INAH','mesoamerica'),
(32,'Zacatecas','La Quemada','Villanueva · valle de Malpaso','Sitio arqueológico','México antiguo','Los vestigios del asentamiento se elevan sobre el valle de Malpaso. Sus construcciones monumentales permiten estudiar una historia regional del norte de Mesoamérica.','Observa cómo se conectan edificios, terrazas y relieve.','¿Por qué conviene comparar relatos sobre un sitio con sus evidencias arqueológicas?','https://www.inah.gob.mx/zonas/112-zona-arqueologica-la-quemada','INAH','mesoamerica')
]
keys=['stateCode','state','name','location','kind','period','history','observe','question','source','institution','route']
entries=[dict(zip(keys,row),id='lugar-'+str(row[0]),reviewed='2026-09-29') for row in rows]
assert len(entries)==32 and len({x['stateCode'] for x in entries})==32
# Links to current visitor information where the historical source is an article.
extra={15:'https://visitateotihuacan.inah.gob.mx/visita/',22:'https://www.gob.mx/cultura/es/articulos/centenario-constitucion-politica-de-los-estados-unidos-mexicanos',23:'https://lugares.inah.gob.mx/es/taxonomy/term/513'}
for e in entries:e['visitorSource']=extra.get(e['stateCode'],e['source'])
json.dump(entries,open('dist/data/heritage.json','w'),ensure_ascii=False,indent=2)
