import json
from pathlib import Path
D=Path('dist/data')
topics=json.loads((D/'topics.json').read_text())
S={
 'ind0':['INEHRM · Independencia','https://www.inehrm.gob.mx/es/inehrm/Independencia'],
 'ind1':['INEHRM · Documentos de la Independencia','https://www.inehrm.gob.mx/es/Constitucion1917/Independencia'],
 'ind2':['INEHRM · Sentimientos de la Nación','https://inehrm.gob.mx/es/Constitucion1917/Sentimientos_de_la_Nacion'],
 'ind3':['UNAM · Independencia y autonomismo','https://historicas.unam.mx/publicaciones/publicadigital/libros/385/independencia_autonomista.html'],
 'ind4':['UNAM · La trigarancia','https://historicas.unam.mx/publicaciones/publicadigital/libros/trigarancia/fuerzas_armadas.html'],
 'rev0':['INEHRM · Revolución social','https://inehrm.gob.mx/es/Constitucion1917/Revolucion_Social'],
 'rev1':['INEHRM · Corrientes revolucionarias','https://inehrm.gob.mx/es/inehrm/ExpDigCorrietRev13-17'],
 'rev2':['INEHRM · Lecturas de historia, tomo II','https://inehrm.gob.mx/recursos/Libros/Antologia_de_lecturas_200_t2.pdf'],
 'ley':['UNAM · Constituciones históricas','https://museodelasconstituciones.unam.mx/constituciones-historicas/'],
 'nac0':['UNAM · Constitución de 1824','https://constitucion-1824.juridicas.unam.mx/'],
 'nac1':['UNAM · Historia constitucional','https://museodelasconstituciones.unam.mx/tema-historia-constitucional/'],
 'nac2':['UNAM · Construcción del Estado mexicano','https://e1.portalacademico.cch.unam.mx/alumno/historiademexico1/unidad4/estadoNacionMexicano/estadoMexicano'],
 'nac3':['Chihuahua · Casa de Juárez','https://www.chihuahua.gob.mx/prensa/reabre-sus-puertas-el-museo-de-la-lealtad-republicana-casa-de-juarez'],
 'mes0':['INAH · Museo Nacional de Antropología','https://lugares.inah.gob.mx/es/node/4237'],
 'mes1':['INAH · Monte Albán','https://www.inah.gob.mx/zonas/94-zona-arqueologica-de-monte-alban'],
 'mes2':['INAH · Historia breve de Teotihuacan','https://www.inah.gob.mx/boletines/historia-breve-de-teotihuacan'],
 'mes3':['INAH · Palenque','https://lugares.inah.gob.mx/es/node/4529'],
 'mes4':['INAH · Grandeza y diversidad','https://mexicograndezaydiversidad.inah.gob.mx/publicacion/capitulo-19.html'],
 'ant0':['The Met · Uruk','https://www.metmuseum.org/es/essays/uruk-the-first-city'],
 'ant1':['The Met · Orígenes de la escritura','https://www.metmuseum.org/ru/essays/the-origins-of-writing'],
 'ant2':['The Met · Ciudades e intercambios','https://www.metmuseum.org/exhibitions/listings/2003/art-of-the-first-cities'],
 'ant3':['The Met · El papiro en Egipto','https://www.metmuseum.org/es/essays/papyrus-in-ancient-egypt'],
 'ant4':['The Met · Teseo y Atenas','https://www.metmuseum.org/ja/essays/theseus-hero-of-athens']
}
# year, date, title, region, theme, narrative, cause, consequence, question, answer, activity, source
rows={
'independencia':[
(1808,'1808','¿Quién gobierna cuando falta el rey?','Nueva España','Gobierno','La crisis de la monarquía española abrió una disputa sobre quién podía ejercer la autoridad. En Nueva España surgieron propuestas de representación y autonomía, sin que todas exigieran todavía separarse de España.','La crisis dinástica debilitó la autoridad reconocida.','Se abrió una discusión sobre soberanía y representación.','¿Autonomía e independencia significan lo mismo?','No. Se podía pedir gobierno propio manteniendo un vínculo con la monarquía.','Dibuja dos escenarios: gobierno propio dentro de una monarquía y separación política.','ind3'),
(1810,'16 de septiembre de 1810','La insurgencia se pone en marcha','Bajío','Conflicto','El levantamiento encabezado por Hidalgo comenzó en Dolores. Se sumaron personas con demandas diversas. La movilización se extendió, pero no tenía un programa compartido por todos ni aseguraba una victoria inmediata.','Conspiraciones políticas y tensiones sociales confluyeron en el levantamiento.','La disputa política se convirtió en una guerra.','¿Por qué no podemos atribuir una sola intención a todos los insurgentes?','Las personas tenían posiciones y necesidades distintas; participar en un movimiento no borraba esas diferencias.','Escribe dos preguntas que harías a participantes de distintos oficios. No inventes sus respuestas como testimonios.','ind0'),
(1810.9,'6 de diciembre de 1810','Un decreto contra la esclavitud','Occidente','Derechos','En Guadalajara, Hidalgo emitió un bando de abolición de la esclavitud. Los documentos insurgentes permiten reconocer demandas sociales, además de la disputa por el gobierno. Un decreto expresa una decisión, pero su aplicación depende del control y las condiciones del territorio.','La insurgencia también cuestionó desigualdades del orden colonial.','La libertad se formuló como una demanda política y social.','¿Cómo comprobarías si el decreto se aplicó?','Buscaría expedientes y testimonios locales, además del propio bando.','Distingue en dos columnas: lo que ordena la norma y las pruebas de su aplicación.','ind1'),
(1811,'1811','Cambian los dirigentes, sigue el movimiento','Norte','Conflicto','Hidalgo fue capturado y ejecutado en Chihuahua en 1811. La guerra no terminó con su muerte: continuaron otros liderazgos y formas de organización. Mirar el norte ayuda a conectar la historia nacional con lugares de memoria cercanos.','La campaña inicial sufrió derrotas y la captura de sus dirigentes.','La insurgencia se reorganizó en otros territorios.','¿Un movimiento depende de una sola persona?','Los dirigentes importan, pero las redes, las demandas y otros participantes pueden sostenerlo.','Ubica Dolores y Chihuahua en un mapa; distingue inicio del movimiento y lugar de cautiverio.','ind0'),
(1813,'14 de septiembre de 1813','La lucha también necesita un proyecto','Sur','Derechos','En Chilpancingo, Morelos presentó los Sentimientos de la Nación ante el Congreso. El texto defendía independencia, soberanía popular y cambios sociales; también sostenía la religión católica como única. Hay que leer juntas sus propuestas, sin convertirlo en un programa del presente.','La insurgencia buscaba organizar una autoridad y un orden político propios.','El Congreso articuló un proyecto de nación.','¿Por qué leer también las ideas que hoy nos resultan distintas?','Porque ayudan a comprender el documento en su época y evitan seleccionar solo lo que coincide con nuestras ideas.','Localiza una propuesta de gobierno y una social; cita el número de punto.','ind2'),
(1814,'22 de octubre de 1814','Una Constitución en medio de la guerra','Occidente','Gobierno','El Congreso insurgente promulgó en Apatzingán el Decreto Constitucional para la Libertad de la América Mexicana. La guerra limitó su aplicación. Su importancia está también en el proyecto político que formuló, no solo en cuánto territorio pudo gobernarse con él.','Los insurgentes necesitaban reglas para su gobierno.','Quedó un antecedente de organización constitucional.','¿Un texto puede ser importante aunque tenga aplicación limitada?','Sí: documenta propuestas e instituciones que deben estudiarse junto con las condiciones que limitaron su alcance.','Relaciona 1813 y 1814: propuesta política y texto constitucional.','ind1'),
(1821.1,'24 de febrero de 1821','Nuevas alianzas y nuevas garantías','Sur','Gobierno','El Plan de Iguala propuso la independencia bajo una monarquía y articuló las garantías de religión, independencia y unión. La convergencia entre fuerzas antes enfrentadas cambió la dirección del proceso. Su programa no era idéntico al de Morelos.','El equilibrio político y militar había cambiado.','Se organizó una alianza que impulsó la consumación.','¿Una alianza demuestra que todos piensan igual?','No. Puede reunir intereses distintos alrededor de un acuerdo temporal.','Compara el Plan de Iguala con los Sentimientos: forma de gobierno, religión y soberanía.','ind4'),
(1821.8,'27 de septiembre de 1821','La independencia abre otra historia','Centro','Gobierno','La entrada del Ejército Trigarante en la capital marcó la consumación. Terminaba una etapa de guerra, pero quedaban problemas de hacienda, territorio y representación. El nuevo país tendría que decidir cómo organizarse.','La alianza trigarante consolidó el cambio político.','Comenzaron nuevos debates sobre la construcción del Estado.','¿Consumación significa que se resolvieron todas las desigualdades?','No. La independencia política y las transformaciones sociales no avanzan automáticamente al mismo ritmo.','Une esta escena con la ruta México como nación y escribe una pregunta pendiente para 1821.','ind4')],
'nacion':[
(1822,'1822–1823','La primera opción fue un imperio','Centro','Gobierno','Agustín de Iturbide encabezó el Primer Imperio mexicano. Los conflictos con el Congreso y la oposición al gobierno mostraron que no había acuerdo definitivo sobre las instituciones. Su caída abrió paso a otro congreso constituyente.','La independencia había dejado abierta la forma de organización política.','Se discutió una solución republicana.','¿La independencia creó inmediatamente una república?','No. Hubo primero una experiencia imperial.','Dibuja una secuencia: independencia, imperio, república.','nac1'),
(1824,'4 de octubre de 1824','Una república con estados','Nacional','Gobierno','La Constitución de 1824 estableció una república federal. La distribución de facultades entre estados y gobierno nacional se convirtió en una cuestión central. Federalismo no significa que cada estado sea un país independiente.','Las provincias demandaban participación en la organización del nuevo Estado.','Se estableció un marco federal para gobernar.','¿Cómo se distingue federación de separación?','Una federación reúne entidades bajo un orden constitucional común, aunque distribuye facultades.','Clasifica asuntos nacionales y locales, aclarando que es una analogía para debatir y no una transcripción de la ley de 1824.','nac0'),
(1836,'1836','El poder cambia de distribución','Nacional','Gobierno','Las Siete Leyes reorganizaron el país con una orientación centralista. Los estados fueron sustituidos por departamentos. Estos cambios permiten comparar cómo una constitución distribuye el poder y quién interviene en las decisiones.','Las disputas sobre gobierno y estabilidad alimentaron proyectos centralistas.','Cambió la relación entre territorios y poder central.','¿Cambiar el nombre de estados a departamentos era solo una palabra?','No: correspondía a una modificación de su organización y relación con el gobierno central.','Compara dos esquemas de gobierno y señala quién decide en cada nivel.','nac1'),
(1854,'1854–1855','Ayutla abre una nueva etapa','Sur','Conflicto','El movimiento de Ayutla se opuso al gobierno de Santa Anna. Su triunfo abrió un periodo de reformas y de elaboración de una nueva constitución. Los cambios políticos surgieron de conflictos, alianzas y decisiones, no de una marcha inevitable.','La oposición cuestionó la concentración del poder.','Un nuevo gobierno impulsó reformas y un congreso.','¿Una crisis tiene un único resultado posible?','No. Los participantes actuaron entre alternativas que debemos reconstruir con fuentes.','Escribe una decisión que enfrentaron los actores y qué información necesitarías para explicarla.','nac1'),
(1857,'5 de febrero de 1857','Derechos que generan debates','Nacional','Derechos','La Constitución de 1857 incorporó garantías individuales y reafirmó la república federal. La oposición a este orden contribuyó a una profunda división política. Un texto constitucional también puede ser objeto de disputa.','El movimiento reformista promovió un nuevo orden jurídico.','Se intensificó el conflicto sobre las instituciones.','¿Por qué una norma puede provocar desacuerdos?','Porque redefine facultades, derechos e intereses y no todos aceptan esos cambios.','Consulta un artículo: explica qué reconoce y qué otra fuente necesitarías para investigar su cumplimiento.','ley'),
(1858,'1858–1861','Dos proyectos se enfrentan','Nacional','Conflicto','La Guerra de Reforma enfrentó a liberales y conservadores. No fue simplemente un desacuerdo entre dos personas: estaban en disputa instituciones y formas de organizar la vida pública. La guerra afectó recursos, comunidades y gobiernos regionales.','La ruptura constitucional profundizó la confrontación política.','La victoria liberal no eliminó las dificultades del país.','¿Qué queda fuera si solo memorizamos dos bandos?','Las experiencias locales, las diferencias internas y los efectos sociales de la guerra.','Construye una pregunta sobre la vida cotidiana durante el conflicto.','nac2'),
(1864,'1864–1866','La República se sostiene desde el norte','Chihuahua','Gobierno','Durante la intervención francesa y el Segundo Imperio, el gobierno de Juárez se desplazó. En Chihuahua, el edificio hoy conocido como Casa de Juárez alojó al Ejecutivo federal. La ubicación de un gobierno también cuenta una historia de resistencia política.','La intervención militar obligó al gobierno republicano a desplazarse.','Chihuahua fue sede de la autoridad republicana durante parte del conflicto.','¿El lugar de una sede de gobierno puede cambiar?','Sí. En este caso el desplazamiento estuvo ligado a la guerra y a la defensa del gobierno republicano.','Conecta esta escena con la ficha Casa de Juárez y explica su valor como lugar de memoria.','nac3'),
(1867,'1867','Restaurar la República, continuar los debates','Nacional','Gobierno','La caída del Segundo Imperio permitió la restauración republicana. Reconstruir instituciones, educación y finanzas siguió siendo un desafío. El triunfo militar no clausuró las discusiones sobre ciudadanía, participación y autoridad.','El avance republicano y el fin del apoyo militar francés debilitaron al Imperio.','Se abrió una etapa de reorganización institucional.','¿Por qué restaurar un gobierno no equivale a resolver todos sus problemas?','Porque los daños de la guerra y las diferencias sociales requieren acciones posteriores.','Cierra la ruta con un cambio y una continuidad entre 1824 y 1867.','nac2')],
'mesoamerica':[
(-2500,'c. 2500 a. C.','Una región, muchas trayectorias','Mesoamérica','Sociedad','El inicio convencional del Preclásico ayuda a organizar un proceso largo. Las comunidades agrícolas y las aldeas se transformaron a ritmos distintos. Mesoamérica es un concepto cultural de los investigadores, no el nombre de un Estado antiguo.','La vida agrícola y las relaciones entre comunidades cambiaron gradualmente.','Se desarrollaron sociedades con historias regionales diferentes.','¿Una fecha de periodo significa que todo cambió ese día?','No. Es una herramienta para ordenar procesos, con límites aproximados.','Distingue un acontecimiento puntual de un proceso que dura siglos.','mes0'),
(-500,'c. 500 a. C.','Una ciudad sobre los valles','Oaxaca','Territorio','Monte Albán se desarrolló en los Valles Centrales de Oaxaca. Sus plazas y edificios permiten investigar organización política y vida ritual. La ciudad tuvo una larga historia: no todas sus construcciones corresponden a un mismo momento.','La concentración de población y poder transformó el paisaje regional.','Monte Albán articuló relaciones con otros asentamientos.','¿Un sitio arqueológico es una fotografía de un solo año?','No. Sus restos corresponden a construcciones, usos y modificaciones sucesivas.','Observa un plano de Monte Albán y formula una pregunta sobre el uso de una plaza.','mes1'),
(200,'c. 200–650 d. C.','Teotihuacan conecta regiones','Altiplano','Intercambio','Teotihuacan fue una gran ciudad con conexiones de larga distancia. En el barrio de Tlailotlacan, la arqueología permite estudiar vínculos con población de origen zapoteco. Las ciudades antiguas podían reunir comunidades de procedencias distintas.','Las redes de intercambio favorecieron contactos y movilidad.','Se produjeron encuentros entre tradiciones y grupos.','¿Una ciudad implica una sola lengua o procedencia?','No. Hay evidencias de diversidad dentro de centros urbanos como Teotihuacan.','Compara un objeto de intercambio con una prueba de residencia: ¿dicen exactamente lo mismo?','mes2'),
(600,'Siglos VI–VIII d. C.','Escrituras que hablan del poder','Área maya','Fuentes','En Palenque, las inscripciones y los edificios aportan información sobre gobernantes y vida ritual. Los textos monumentales expresan perspectivas del poder. No cuentan de la misma manera la experiencia de todos los habitantes.','Las élites usaron monumentos e inscripciones para comunicar autoridad.','Se conservaron registros que los investigadores interpretan y contrastan.','¿Quién podría quedar fuera de una inscripción real?','Personas y trabajos que el gobernante no eligió representar.','Escribe una pregunta que una inscripción pueda responder y otra que requiera herramientas o viviendas.','mes3'),
(750,'c. 650–900 d. C.','Las ciudades también se transforman','Mesoamérica','Sociedad','Los cambios de los centros urbanos no ocurrieron simultáneamente. Una ciudad puede perder población o poder mientras otras crecen. Abandonar edificios no significa que desaparezcan todos sus habitantes o su cultura.','Las transformaciones deben estudiarse con evidencias de cada región.','Cambian las redes y los centros de poder.','¿Es correcto decir que una cultura desaparece porque una ciudad declina?','No: hay que investigar movilidad, continuidad y transformaciones de las comunidades.','Busca qué evidencia distinguiría abandono de un edificio y despoblamiento regional.','mes0'),
(1400,'Siglos XIV–XVI','Nombrar el pasado desde otra época','Altiplano','Fuentes','Los mexicas conocieron Teotihuacan mucho después de su apogeo y usaron el nombre por el que la conocemos. Sus relatos sobre el lugar expresan una relación cultural con el pasado; no prueban que ellos construyeran la ciudad.','Sociedades posteriores interpretaron ruinas y lugares anteriores a ellas.','Se produjeron nombres y relatos que siguen influyendo en nuestra mirada.','¿El nombre actual identifica a los constructores?','No necesariamente. Un nombre puede ser posterior a la fundación del lugar.','Separa nombre conocido, constructores e interpretación posterior en tres tarjetas.','mes2'),
(1952,'1952','Un hallazgo abre nuevas preguntas','Chiapas','Fuentes','Alberto Ruz L’Huillier localizó la tumba de Pakal en el Templo de las Inscripciones de Palenque. El hallazgo cambió las preguntas de investigación. Los objetos se entienden mejor al conservar la información de su contexto.','La investigación arqueológica exploró estructuras del templo.','Se amplió el conocimiento de prácticas funerarias y del poder dinástico.','¿Qué pierde un objeto si se extrae sin registrar su contexto?','Información sobre su ubicación y su relación con otras evidencias.','Diseña una ficha de registro: lugar, material, asociación y pregunta, sin tocar ni retirar piezas.','mes3'),
(2026,'Actualidad','Los pueblos no son solo pasado','México y Centroamérica','Sociedad','Los pueblos originarios forman parte del presente. Sus lenguas, conocimientos y reivindicaciones han cambiado históricamente. Estudiarlos exige reconocer diversidad y voces propias, sin tratarlos como copias inmóviles de sociedades antiguas.','Las comunidades han vivido continuidades, cambios y relaciones de poder.','El patrimonio se vincula con derechos y experiencias actuales.','¿Por qué un museo no sustituye escuchar a una comunidad viva?','Porque el presente incluye voces y decisiones que no caben en una colección de objetos antiguos.','Consulta una fuente producida por una comunidad y registra autoría, lengua y propósito.','mes4')],
'antigua':[
(-3500,'c. 3500–3000 a. C.','Uruk: organizar una ciudad','Mesopotamia','Sociedad','Uruk creció en la llanura del sur de Mesopotamia. La concentración de población exigía coordinar producción, almacenamiento e intercambios. Una ciudad se estudia también a través del trabajo cotidiano, no únicamente de grandes monumentos.','La concentración de actividades aumentó la necesidad de coordinación.','Surgieron formas complejas de administración urbana.','¿Qué necesita organizar una ciudad además de construir casas?','Agua, alimentos, trabajo, intercambios y decisiones colectivas.','Dibuja una red con tres necesidades urbanas y quiénes participan en ellas.','ant0'),
(-3200,'Finales del IV milenio a. C.','Registrar para administrar','Mesopotamia','Fuentes','En Uruk, los primeros registros escritos se relacionaron con la contabilidad de bienes. Las tablillas de arcilla documentan actividades administrativas. Escribir no significaba que toda la población supiera leer o tuviera la misma participación en el poder.','Las instituciones necesitaban registrar recursos y operaciones.','La escritura preservó información que hoy permite investigar.','¿Una lista de bienes cuenta toda la vida de una comunidad?','No: muestra lo que se registró, pero deja fuera experiencias y relaciones.','Inventa un registro de cinco objetos y marca claramente que es una simulación escolar.','ant1'),
(-3000,'Tercer milenio a. C.','Las ciudades se conectan','Asia occidental','Intercambio','Las ciudades de Asia occidental participaron en redes de circulación de materiales y objetos. Un bien que viaja es una pista sobre conexiones, pero no demuestra por sí solo que dos ciudades tuvieran el mismo gobierno.','La búsqueda de materiales y los intercambios conectaron regiones.','Circularon objetos, técnicas e ideas.','¿Un objeto extranjero demuestra una conquista?','No. También pudo llegar mediante intercambio, regalo u otra forma de circulación.','Propón dos explicaciones para un hallazgo y una evidencia para distinguirlas.','ant2'),
(-2500,'Egipto antiguo · varios periodos','Un río y muchos trabajos','Valle del Nilo','Territorio','El papiro crecía en el ambiente del Nilo y sirvió para fabricar soportes de escritura y otros objetos. Estudiar un material permite relacionar entorno, técnica y trabajo sin reducir una sociedad a sus monumentos funerarios.','Las comunidades aprovecharon recursos de su entorno.','Se desarrollaron técnicas con usos cotidianos y simbólicos.','¿El entorno determina por completo la forma de vivir?','No. Ofrece condiciones, pero las personas toman decisiones y desarrollan técnicas.','Relaciona recurso, técnica y uso en una cadena y compárala con un material actual.','ant3'),
(-2000,'Egipto antiguo · varios periodos','Un objeto tiene más de una historia','Valle del Nilo','Fuentes','El papiro tuvo dimensiones prácticas y simbólicas. Una pieza puede estudiarse por su material, por su uso y por su presencia en representaciones. Cada pregunta requiere observar evidencias diferentes.','Los materiales formaron parte de prácticas y creencias.','Los objetos conservaron información sobre distintas dimensiones de la vida.','¿Qué diferencia hay entre observar e interpretar?','Observar describe rasgos; interpretar propone su significado en contexto y necesita argumentos.','Elige una pieza del museo y escribe dos observaciones y una interpretación.','ant3'),
(-500,'Siglo V a. C.','Atenas cuenta sus relatos','Mundo griego','Fuentes','Los relatos de Teseo se relacionaron con la identidad de Atenas. Un mito puede estudiarse como expresión cultural y política sin asumir que sus episodios ocurrieron literalmente. Las representaciones también tienen historia.','Las comunidades usaron relatos para expresar vínculos e identidades.','Los mitos circularon en imágenes y narraciones.','¿Un mito carece de valor para la historia?','No. Es evidencia de creencias y formas de representación, aunque no sea prueba literal de sus sucesos.','Compara una representación mítica con una inscripción: ¿qué pregunta harías a cada fuente?','ant4'),
(-450,'Atenas clásica','Participar no era un derecho universal','Mundo griego','Gobierno','La democracia ateniense tuvo límites de participación. No equivalía al sufragio universal contemporáneo. Comparar vocabularios políticos exige preguntar quién podía intervenir y quién quedaba excluido, sin suponer que una misma palabra conserva idéntico significado.','Las instituciones de la polis definían categorías de participación.','Una parte de la población podía intervenir en decisiones políticas.','¿Basta la palabra democracia para saber quién participa?','No: hay que revisar las reglas de ciudadanía y participación en cada contexto.','Haz una lista de preguntas para comparar participación antigua y actual, evitando equipararlas.','ant4'),
(2026,'Actualidad','Una pieza, preguntas abiertas','Museos y archivos','Fuentes','La arqueología y la lectura de documentos revisan explicaciones sobre el mundo antiguo. Investigar no consiste en rellenar silencios con certezas: hay que indicar lo observado, lo inferido y lo que todavía no sabemos.','Nuevos hallazgos y preguntas permiten revisar interpretaciones.','El conocimiento histórico puede ampliarse y corregirse.','¿Reconocer una duda debilita una investigación?','No. Explicitar los límites de la evidencia hace más clara la explicación.','Cierra con una ficha: evidencia, interpretación, límite y fuente consultada.','ant1')],
'revolucion':[
(1910,'1910','Un país quiere cambios','Nacional','Gobierno','El antirreeleccionismo de Madero cuestionó la permanencia de Díaz en el poder. A la oposición política se sumaron demandas sociales distintas. La movilización de 1910 abrió una revolución plural, no un programa uniforme.','La concentración del poder convivía con conflictos sociales y políticos.','El levantamiento abrió una lucha por el gobierno y por reformas.','¿Votar y repartir tierra son la misma demanda?','No. Son problemas diferentes que podían coincidir en la oposición al régimen.','Clasifica demandas políticas, laborales y agrarias.','rev0'),
(1911.1,'Mayo de 1911','Ciudad Juárez cambia el rumbo','Chihuahua','Conflicto','La toma de Ciudad Juárez fue decisiva en la etapa maderista. Los acuerdos de mayo contribuyeron a la renuncia de Díaz. El norte fue un espacio de movilización y negociación conectado con el resto del país.','El avance rebelde debilitó al gobierno porfirista.','Se abrió una transición política, sin resolver todas las demandas.','¿Por qué una ciudad fronteriza puede ser importante en una guerra?','Por sus conexiones, recursos y valor político; el peso concreto debe investigarse con fuentes.','Localiza Juárez y pregunta qué conexiones territoriales favorecían su importancia.','rev2'),
(1911.9,'28 de noviembre de 1911','La tierra, una demanda central','Morelos','Derechos','El Plan de Ayala expresó demandas de restitución y reparto de tierras. El zapatismo cuestionó la respuesta del gobierno de Madero al problema agrario. La salida de Díaz no había terminado los conflictos de los pueblos.','Las comunidades reclamaban respuestas a despojos y problemas de propiedad.','Se profundizó la ruptura entre zapatismo y maderismo.','¿Cambiar de presidente resuelve por sí solo un conflicto agrario?','No: también hacen falta decisiones sobre propiedad y derechos de los pueblos.','Relaciona una demanda del Plan con el problema que intentaba atender.','rev0'),
(1913,'Febrero de 1913','Una ruptura y nuevas alianzas','Centro','Conflicto','El golpe contra Madero y su asesinato abrieron una nueva fase. Victoriano Huerta tomó el poder y distintas fuerzas se organizaron en su contra. Compartir adversario no eliminó las diferencias entre los movimientos.','El golpe rompió el orden del gobierno maderista.','Se formó una nueva oposición armada.','¿Por qué una alianza puede romperse después de vencer?','Porque sus integrantes pueden mantener objetivos incompatibles sobre el futuro.','Distingue objetivo inmediato y proyecto de largo plazo.','rev1'),
(1914.4,'1914','El norte y el sur no son un solo bloque','Norte y sur','Territorio','Villismo, zapatismo y constitucionalismo reunieron fuerzas con bases regionales y proyectos diferentes. Sus relaciones cambiaron con la guerra. Los mapas de movimientos deben leerse con fecha: no son fronteras fijas.','Las demandas y condiciones variaban entre territorios.','La lucha contra Huerta reunió fuerzas que después se enfrentarían.','¿Un mapa de un año sirve sin cambios para toda la Revolución?','No. Las zonas de acción y las alianzas cambiaron.','Elige dos movimientos y compara región, demanda y fuente.','rev1'),
(1914.8,'Octubre–noviembre de 1914','La Convención busca un acuerdo','Aguascalientes','Gobierno','La Convención intentó resolver diferencias entre fuerzas revolucionarias. Sus debates mostraron la dificultad de construir una autoridad común. Los acuerdos políticos fueron tan importantes para el proceso como las campañas militares.','La derrota de Huerta dejó abierta la cuestión de quién gobernaría.','Las diferencias desembocaron en nuevos enfrentamientos.','¿Qué dificulta llegar a acuerdos después de una guerra?','Los proyectos distintos, las desconfianzas y los intereses regionales.','Redacta dos condiciones necesarias para una negociación y justifícalas.','rev1'),
(1915,'1915','La lucha también se vive en el campo','Regiones de México','Sociedad','La guerra alteró trabajo, abastecimiento y vida familiar. Las comunidades vivieron experiencias distintas según el territorio y los ejércitos presentes. Un relato centrado en generales no explica por sí solo estas transformaciones.','La movilización y los combates afectaron la vida cotidiana.','Se produjeron desplazamientos y dificultades de abastecimiento.','¿Qué fuente buscarías para conocer la experiencia de una familia?','Cartas, testimonios o registros locales, contrastados con otras evidencias.','Elabora preguntas de investigación; no inventes un testimonio y lo presentes como documento.','rev2'),
(1916,'1916–1917','Debatir el país que se quiere','Querétaro','Gobierno','El Congreso Constituyente sesionó en Querétaro. Los debates dieron forma a disposiciones sobre educación, propiedad y trabajo. El texto resultante se comprende mejor al relacionarlo con las demandas y conflictos anteriores.','La lucha abrió una discusión sobre el nuevo orden institucional.','El Constituyente redactó una nueva Constitución.','¿Una constitución es solo obra de una persona?','No. Su elaboración incluye propuestas, debates y decisiones de una asamblea.','Busca un derecho en el texto original y relaciónalo con una demanda de la ruta.','ley'),
(1917,'5 de febrero de 1917','Los derechos llegan a la Constitución','Nacional','Derechos','La Constitución promulgada en 1917 incluyó disposiciones sociales: educación, tierra y trabajo. Reconocer un derecho en una norma fue un cambio importante; su cumplimiento exigió procesos posteriores. La violencia tampoco concluyó de inmediato.','Los debates constitucionales respondieron a conflictos políticos y sociales.','Se estableció un nuevo marco jurídico.','¿Cómo distinguir un derecho escrito de su cumplimiento?','La norma muestra lo reconocido; otras fuentes permiten estudiar la práctica.','Formula un indicador para investigar el cumplimiento de un derecho, sin confundirlo con su sola existencia.','ley'),
(1920,'Después de 1917','¿Cuándo termina una revolución?','Nacional','Fuentes','La respuesta depende de qué se investiga: lucha armada, reorganización política o cambios sociales. Elegir un corte cronológico exige explicarlo. El estudio de las consecuencias continúa más allá de la promulgación constitucional.','Los cambios revolucionarios avanzaron con ritmos distintos.','Existen periodizaciones diferentes, sustentadas en preguntas distintas.','¿Dos fechas finales diferentes prueban que una historia es falsa?','No necesariamente: pueden responder a dimensiones diferentes, si explican sus criterios y evidencias.','Propón un criterio para cerrar la ruta y defiéndelo con un acontecimiento y una fuente.','rev2')]
}
images={'mesoamerica':'mesoamerica-classroom.webp','independencia':'independencia.webp','nacion':'nacion.webp','antigua':'antigua.webp','revolucion':'revolucion-1910.webp'}
chapters=[]
for t in topics:
 for i,r in enumerate(rows[t['id']]):
  y,date,title,region,theme,text,cause,effect,q,a,task,src=r
  image=images[t['id']]
  if t['id']=='revolucion':image='revolucion-1917.webp' if i>=7 else 'revolucion-1911.webp' if i in [2,4,6] else image
  chapters.append(dict(id=f"{t['id']}-{i+1}",route=t['id'],year=y,date=date,title=title,region=region,theme=theme,text=text,cause=cause,effect=effect,question=q,answer=a,activity=task,source=S[src],image='/assets/'+image))
 t['chapters']=[c['id'] for c in chapters if c['route']==t['id']]
 # Preserve legacy dates and core route text; independent dossier carries fuller sequence.
 for c in [c for c in chapters if c['route']==t['id']]:
  if not any(s[1]==c['source'][1] for s in t['sources']):t['sources'].append([*c['source'],'Contexto y lectura por episodios'])
(D/'chapters.json').write_text(json.dumps(chapters,ensure_ascii=False,indent=2))
(D/'topics.json').write_text(json.dumps(topics,ensure_ascii=False,indent=2))
print('Chapters:',len(chapters))
