import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from '/root/.codex/skills/builtins/presentations/container_tools/artifact_tool_utils.mjs';
const root='/workspace/scratch/51e91ec16eac/atlas-deck';
const topics=JSON.parse(await fs.readFile('/workspace/scratch/51e91ec16eac/atlas/dist/data/topics.json','utf8'));
const family=resolvePresentationFont();
const p=Presentation.create({slideSize:{width:1280,height:720}});
function text(s,v,x,y,w,h,size,color='#162b2f',bold=false){const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=v;q.text.style={typeface:family,fontSize:size,color,bold,autoFit:'none'};return q}
function slide(title,body,notes,dark=false){const s=p.slides.add();s.background.fill=dark?'#162b2f':'#f6f0e4';text(s,title,70,65,1130,150,48,dark?'#fffaf1':'#162b2f',true);text(s,body,75,245,1110,355,30,dark?'#efe5d3':'#355155');text(s,'Atlas del Tiempo · Historia para el aula',75,650,1000,28,18,dark?'#d99b52':'#c95f40');s.speakerNotes.textFrame.setText(notes);return s}
slide('México: historias que se conectan','Ciudades, independencia, construcción de la nación y revolución.\n\nPregunta para comenzar: ¿cómo cambia nuestra explicación cuando consultamos una fuente?', 'Propuesta para primaria alta y secundaria. Seleccione una ruta para profundizar. El recorrido no pretende cubrir todos los procesos de la historia de México.',true);
for(const id of ['mesoamerica','independencia','nacion','revolucion']){const t=topics.find(x=>x.id===id);slide(t.title,t.question+'\n\n'+t.summary,t.classroom.join('\n\n')+'\n\nFuentes:\n'+t.sources.map(x=>x[0]+' '+x[1]).join('\n'))}
slide('Una fecha abre una pregunta','1810 · Comienza la insurgencia.\n1821 · Se consuma la independencia.\n1824 · Se establece una Constitución federal.\n1910 · Comienza el movimiento revolucionario.\n1917 · Se promulga una nueva Constitución.', 'Pregunte: ¿la promulgación de una ley significa que todos sus derechos se cumplen de inmediato? Fuentes: https://museodelasconstituciones.unam.mx/constituciones-historicas/ y https://inehrm.gob.mx/es/Constitucion1917/Revolucion_Social');
slide('No todas las afirmaciones son iguales','Hecho documentado: se sostiene con evidencias contrastables.\n\nInterpretación: propone una explicación de las evidencias.\n\nTradición o mito: expresa una memoria o creencia; no equivale por sí sola a una crónica literal.', 'Pida ejemplos de las fichas de Atlas. Una interpretación no significa una opinión sin evidencia. Los mitos tienen valor histórico como expresiones culturales. Fuentes de ejemplo: https://www.inah.gob.mx/boletines/historia-breve-de-teotihuacan');
slide('Tu comunidad también tiene historia','Elige un lugar, una fotografía o un testimonio.\n\nRegistra quién lo produjo, cuándo y para qué.\n\nContrástalo con otra fuente.\n\nComparte una conclusión y una pregunta que siga abierta.', 'Actividad final: parejas, 10 minutos. Evaluación: referencia a una fuente, distinción entre hecho e interpretación y reconocimiento de una pregunta abierta. Archivo de consulta: https://memoricamexico.gob.mx/',true);
await (await PresentationFile.exportPptx(p)).save(root+'/build/candidate.pptx');
await finalizePresentation({workspaceDir:root,candidatePath:root+'/build/candidate.pptx',finalPath:root+'/output/panorama-mexico.pptx',pythonExecutable:process.env.CODEX_PRIMARY_RUNTIME_PYTHON,integrityValidatorPath:'/root/.codex/skills/builtins/presentations/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:'/root/.codex/skills/builtins/presentations/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[family]},verifyArtifactToolImport:true,receiptPath:root+'/build/validation.json'});
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(root+'/build/slide-'+(i+1)+'.png',new Uint8Array(await b.arrayBuffer()))}
console.log('Deck finalized and rendered');
